### ISSUE TITLE
participate in upcoming FORCE2021 SCIWG collaboration sprint

### ISSUE THREAD

**Issue by alee** [SciCodes/Planning#1]
A collaboration sprint to be held in conjunction with FORCE2021, currently slated for 4 hours on December 6th and December 10th 

coordinate on a variety of issues to make up for our missed workshop this fall

- crosswalk resource metadata with codemeta / cff
- collaborative writing / editing on TBD
- different aspects for adopting best practices
- hackathon: develop a harvester to gather data from respective resources (OAI-PMH or ResourceSync or ...?)
- common API to all implement (for access to resources?)
- brainstorm how to track impact of good metadata
- improve documentation on the codemeta site, links to scicodes + tools
- come up with an as simple as possible / broad checklist for FAIR research software with a concrete example illustrating each axis
- add more here

**Comment by tmorrell** [comment]
Now broken out into a project board: https://github.com/orgs/SciCodes/projects/1/views/1

**Comment by tmorrell** [comment]
The Force2021 Hackathon document is available at https://docs.google.com/document/d/1r5nIc5JdoiZmsTMqQhYYSGqW0fcfuO9WrbVi1amfJYY/edit#
