### ISSUE TITLE
How to sign up to SciCodes?

### ISSUE THREAD

**Issue by stain** [SciCodes/Planning#13]
Hi,

Would it be good to add something to https://scicodes.net/ on how to follow meetings and sign up?

I found https://github.com/SciCodes/meeting-info with "Late February" meeting notes, I assume these are from 2021, are there later meeting/notes? Perhaps the website should link to this repository?

**Comment by tmorrell** [comment]
Hi - sorry for the delay in responding. All our meetings and info are now listed at https://scicodes.net/meetings/
