### ISSUE TITLE
code of conduct examples

### ISSUE THREAD

**Issue by alee** [SciCodes/Planning#15]
UPDATE: currently leaning towards Django + Jupyter CoC for simplicity:

- https://jupyter.org/governance/conduct/code_of_conduct.html
- https://www.djangoproject.com/conduct/

------

https://www.debian.org/intro/diversity

https://jupyter.org/governance/conduct/code_of_conduct.html

https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html

https://www.djangoproject.com/conduct/

https://www.opencon.community/code_of_conduct

**Comment by tmorrell** [comment]
Working draft https://docs.google.com/document/d/1uobU8TpvroExydYAfR8VOcuFnWIngAVEsGTy6X5pXA0/edit#
