### ISSUE TITLE
establish governance policies for scicodes membership

### ISSUE THREAD

**Issue by alee** [SciCodes/Planning#6]
who should be a member of scicodes? 

- whatever process and requirements we decide on should come from this current community and evolve over time as needed
- need clear mission statement

Current mission-ish statement from scicodes.net:

> The SciCodes Consortium is for editors and maintainers of academic discipline and institutional software registries and repositories. The Consortium, still in its development phase, will enable its members to:
> 
> share work methods, marketing ideas, and communication practices;
demonstrate unique aspects of our respective services, discuss challenges and share solutions to common issues that arise in managing our resources;
work cooperatively to speed adoption of the CodeMeta and CFF standards and better enable software citation, recognition, and dissemination;
work towards a virtual registry standard to enable searching across multiple software registries.

**Comment by tmorrell** [comment]
Now documented at https://scicodes.net/policies/
